"""Remove Queue

Revision ID: 49b2d4f8f942
Revises: c3c3fac65313
Create Date: 2020-10-04 19:06:02.164808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b2d4f8f942'
down_revision = 'c3c3fac65313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queues')
    op.create_foreign_key(None, 'raids', 'guilds', ['guild_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raids', type_='foreignkey')
    op.create_table('queues',
    sa.Column('raid_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['raid_id'], ['raids.id'], name='queues_raid_id_fkey')
    )
    # ### end Alembic commands ###
