"""Alter Profile Options

Revision ID: 5f40e81aad01
Revises: 49b2d4f8f942
Create Date: 2020-10-06 14:08:09.496588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f40e81aad01"
down_revision = "49b2d4f8f942"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "airport")
    op.drop_column("profiles", "island_name")
    op.drop_column("profiles", "is_northern")
    op.drop_column("profiles", "fruit")
    op.drop_column("profiles", "flower")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("flower", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "profiles", sa.Column("fruit", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "profiles",
        sa.Column("is_northern", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "profiles",
        sa.Column("island_name", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "profiles", sa.Column("airport", sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
