"""Add Raid Database

Revision ID: c3c3fac65313
Revises: e04fb668229b
Create Date: 2020-08-22 17:44:00.331888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c3fac65313'
down_revision = 'e04fb668229b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('set_level', sa.BIGINT(), nullable=False),
    sa.Column('set_xp', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('set_level')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('friend_code', sa.Text(), nullable=True),
    sa.Column('island_name', sa.Text(), nullable=True),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('fruit', sa.Text(), nullable=True),
    sa.Column('is_northern', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('flower', sa.Text(), nullable=True),
    sa.Column('airport', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=True),
    sa.Column('host_banned', sa.Boolean(), nullable=True),
    sa.Column('reports_created_count', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('xp', sa.BIGINT(), nullable=True),
    sa.Column('times_hosted', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raids',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('guild_id', sa.BIGINT(), nullable=True),
    sa.Column('pokemon', sa.Text(), nullable=True),
    sa.Column('shiny', sa.Boolean(), nullable=True),
    sa.Column('gmax', sa.Boolean(), nullable=True),
    sa.Column('host_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queues',
    sa.Column('raid_id', sa.BIGINT(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('guild_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['raid_id'], ['raids.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queues')
    op.drop_table('raids')
    op.drop_table('users')
    op.drop_table('profiles')
    op.drop_table('levels')
    # ### end Alembic commands ###
